repos:
  - repo: local
    hooks:
      - id: spotless-apply
        name: Apply spotless (java code formatter)
        entry: bash -c ./gradlew javaFormattingApply
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-json
      - id: check-xml
