repos:
  - repo: local
    hooks:
      - id: formatting-test-docs
        name: Execute Gradle Check, Test, AsciidocTask
        entry: bash -c ./gradlew check --info
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: publish-docs
        name: Execute Gradle GitPublish
        language: system
        entry: bash -c ./gradlew gitPublishPush
        pass_filenames: false
