services:
  spring-boot:
    image: spring-boot-app
    container_name: spring-boot-container
    ports:
      - "8081:8081"
    networks:
      - member-network
    volumes:
      - ./logs:/var/log/app
