# docker network member-network

services:
  member:
    image: ${DOCKER_USERNAME}/socketing:member-service
    container_name: member-service-app
    ports:
      - "8081:8081"
    networks:
      - member-network
    volumes:
      - ./logs:/app/logs

networks:
  member-network:
    external: true
