server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_socketing
    username: jeein
    password: 12345678
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
eureka:
  client:
    enabled: false
logging:
  config: classpath:logback-spring.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
    httpexchanges:
      enabled: true
  info:
    java:
      enabled: true
    os:
      enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    redis:
      enabled: true
    info:
      enabled: true
    show-details: always
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: false
  api-docs:
    path: /api/v1/members/api/json
  swagger-ui:
    path: /api/v1/members/api/docs
    operations-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
